FROM ubuntu:latest

WORKDIR /code

COPY . .

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip

RUN pip install pymongo --break-system-packages

CMD ["python3", "-u", "exportar.py"]