FROM bde2020/hadoop-base:2.0.0-hadoop2.7.4-java8

ENV PIG_VERSION 0.17.0

RUN curl -O https://downloads.apache.org/pig/pig-${PIG_VERSION}/pig-${PIG_VERSION}.tar.gz && \
    tar -xvf pig-${PIG_VERSION}.tar.gz && \
    mv pig-${PIG_VERSION} /opt/pig && \
    ln -s /opt/pig/bin/pig /usr/local/bin/pig && \
    rm pig-${PIG_VERSION}.tar.gz

ENV PIG_HOME /opt/pig
ENV PATH $PATH:$PIG_HOME/bin

CMD ["/bin/bash"]